# Generated by Django 2.2.4 on 2020-03-25 05:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies_register', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Aventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Comedie', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Famille', 'Family'), ('Musical', 'Musical'), ('Mystere', 'Mystery'), ('Romance', 'Romance'), ('Science-Fiction', 'Science-Fiction'), ('Guerre', 'War'), ('Western', 'Western')], max_length=120),
        ),
        migrations.AlterField(
            model_name='movies',
            name='score',
            field=models.IntegerField(),
        ),
    ]
