# Generated by Django 2.2.4 on 2020-03-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_register', '0005_auto_20200325_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
